// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Code  string `form:"code"`
	State string `form:"state"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
}

type UserDetailResp struct {
	Name string `json:"name"`
}
