// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: UserDetailHandler(serverCtx),
				},
			}...,
		),
	)
}
